# MIPANSUSUSU 

## Contents
- [Packages](#section1)
- [Datasets Cleaning](#section2)
    - [HDB Resale 2020](#subsection2.1)
    - [MRT Coordinates](#subsection2.2)
    - [Mall Coordinates](#subsection2.3)
    - [BusStop Coordinates](#subsection2.4)
    - [Import All Other Relevant Datasets](#subsection2.5)
- [General Functions](#section3)

## Packages<a id="section2"></a>

In [1]:
import json
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import urllib

## Datasets Cleaning<a id="section1"></a>

We first begin by cleaning raw data sets in order to consolidate related data, as well as process data for later data visualisation and data processing.

<div class="alert alert-block alert-success">
<b>List of Key Datasets:</b> 
The Key Datasets we will be using are summarised below (alongside links to online data files if applicable)
  <li><b><a href="https://data.gov.sg/dataset/resale-flat-prices">HDB Resale Data</a></b>: Resale price, town, blk, street_name, postal code, longitude and latitude of HDB blocks</li>
  <li><b>Malls</b>: Shopping Mall Names, region, longitude and latitude</li>
  <li><b>MRT</b>: MRT locations, longitude and latitude</li>
  <li><b><a href="https://github.com/cheeaun/busrouter-sg/blob/master/data/3/stops.onemap.json">Buses</a></b>: BusStop Numbers, longitude and latitude</li>
</div> 


<a href="https://docs.onemap.sg/#search">OneMap API</a> was utilised in mapping corresponding latitude and longitude data to respective locations.

Due to the length of time taken to query onemap's API to attain geolocation data, we have prerun the queries and exported the data into a csv file for any later data processing and visualisation. The below variable has been set to 'False' to prevent rerunning of those specific queries when restarting the kernel

We necessary we converted json files with raw data to csv for easier processing through an <a href="https://www.convertcsv.com/json-to-csv.htm">online converting site</a>.

In [2]:
rerun = True

### HDB Resale 2020<a id="subsection2.1"></a>

In [12]:
HDB_coordinates = pd.read_csv("raw_HDB_coordinates.csv")
HDV_resale_2020_raw = pd.read_csv("raw_resale_flat_prices_2017_2020.csv")
HDB_resale_2020 = HDV_resale_2020_raw.merge(HDB_coordinates, how='inner', left_on=['town','block'], right_on=['town','block'])

#export the full dataframe for hdb with longitude and latitudes into csv
HDB_resale_2020.to_csv('clean_HDBresale2020.csv')

HDB_resale_2020

,month,town,flat_type,block,STREETreet_name,STREETorey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,street_name,lat,long
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVENUENUE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0,ANG MO KIO AVE 10,1.362005,103.853880
1,2017-05,ANG MO KIO,2 ROOM,406,ANG MO KIO AVENUE 10,10 TO 12,44.0,Improved,1979,61 years 01 month,235000.0,ANG MO KIO AVE 10,1.362005,103.853880
2,2018-03,ANG MO KIO,2 ROOM,406,ANG MO KIO AVENUE 10,01 TO 03,44.0,Improved,1979,60 years 02 months,202000.0,ANG MO KIO AVE 10,1.362005,103.853880
3,2018-03,ANG MO KIO,2 ROOM,406,ANG MO KIO AVENUE 10,01 TO 03,44.0,Improved,1979,60 years 02 months,210000.0,ANG MO KIO AVE 10,1.362005,103.853880
4,2018-05,ANG MO KIO,2 ROOM,406,ANG MO KIO AVENUE 10,07 TO 09,44.0,Improved,1979,60 years 01 month,220000.0,ANG MO KIO AVE 10,1.362005,103.853880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74059,2020-08,TOA PAYOH,EXECUTIVE,240,LORONG 1 TOA PAYOH,01 TO 03,146.0,Maisonette,1986,65 years 03 months,760000.0,LOR 1 TOA PAYOH,1.340876,103.850830
74060,2020-08,TOA PAYOH,EXECUTIVE,101B,LORONG 2 TOA PAYOH,04 TO 06,144.0,Apartment,1993,71 years 08 months,901000.0,LOR 2 TOA PAYOH,1.339599,103.847605
74061,2020-08,WOODLANDS,EXECUTIVE,176,WOODLANDS STREET 13,04 TO 06,184.0,Apartment,1994,72 years 05 months,670888.0,WOODLANDS ST 13,1.433579,103.778353
74062,2020-08,YISHUN,EXECUTIVE,361,YISHUN RING ROAD,01 TO 03,145.0,Maisonette,1988,66 years 10 months,610000.0,YISHUN RING RD,1.428325,103.845908
74063,2020-08,YISHUN,EXECUTIVE,258,YISHUN STREET 22,01 TO 03,154.0,Maisonette,1985,63 years 09 months,530000.0,YISHUN ST 22,1.435156,103.839804

### MRT Coordinates<a id="subsection2.2"></a>

In [8]:
MRT_coords = pd.read_csv("clean_MRT.csv")

MRT_coords

,OBJECTID,STN_NAME,STN_NO,X,Y,Latitude,Longitude,COLOR
0,12,ADMIRALTY MRT STATION,NS10,24402.1063,46918.1131,1.440585,103.800998,RED
1,16,ALJUNIED MRT STATION,EW9,33518.6049,33190.0020,1.316433,103.882893,GREEN
2,33,ANG MO KIO MRT STATION,NS16,29807.2655,39105.7720,1.369933,103.849553,RED
3,81,BAKAU LRT STATION,SE3,36026.0821,41113.8766,1.388093,103.905418,OTHERS
4,80,BANGKIT LRT STATION,BP9,21248.2460,40220.9693,1.380018,103.772667,OTHERS
...,...,...,...,...,...,...,...,...
182,175,WOODLANDS SOUTH MRT STATION,TE3,23607.8309,45444.7113,1.427260,103.793863,OTHERS
183,146,WOODLEIGH MRT STATION,NE11,32173.3186,35706.3794,1.339190,103.870808,PURPLE
184,6,YEW TEE MRT STATION,NS5,18438.9791,42158.0124,1.397535,103.747431,RED
185,41,YIO CHU KANG MRT STATION,NS15,29294.1283,40413.0820,1.381756,103.844944,RED
186,13,YISHUN MRT STATION,NS13,28187.6787,45686.0701,1.429443,103.835005,RED

### Mall Coordinates<a id="subsection2.3"></a>

In [34]:
list_of_shopping_mall = [
    '100 AM', '313@Somerset', 'Aperia', 'Balestier Hill Shopping Centre', 'Bugis Cube', 
    'Bugis Junction', 'Bugis+', 'Capitol Piazza', 'Cathay Cineleisure Orchard', 'City Gate', 
    'City Square Mall', 'CityLink Mall', 'Clarke Quay Central', 'Duo', 'Far East Plaza', 'Funan', 
    'Great World City', 'HDB Hub', 'Holland Village Shopping Mall', 'ION Orchard', 'Junction 8', 
    'Knightsbridge[1]', 'Liang Court', 'Liat Towers', 'Lucky Plaza', 'Marina Bay Financial Centre Tower 3', 
    'Marina Bay Link Mall', 'Marina Bay Sands', 'Marina One', 'Marina Square', 'Midpoint Orchard', 'Millenia Walk', 
    'Mustafa Shopping Centre', 'Ngee Ann City', 'Orchard Central', 'Orchard Gateway', 'Orchard Plaza', 
    'Orchard Shopping Centre', 'Palais Renaissance', 'Peoples Park Centre', 'Peoples Park Complex', 
    'Plaza Singapura', 'PoMo', 'Raffles City', 'Scotts Square', 'Serangoon Plaza', 'Shaw House and Centre', 
    'Sim Lim Square', 'Singapore Shopping Centre', 'Square 2', 'Suntec City', 'Tanglin Mall', 'Tangs', 
    'Tanjong Pagar Centre', 'Tekka Centre', 'The Centrepoint', 'The Paragon', 'The Poiz [2]', 
    'The Shoppes at Marina Bay Sands', 'The South Beach', 'Thomson Plaza', 'United Square, The Kids Learning Mall', 
    'Velocity', 'Wheelock Place', 'Wisma Atria', 'Zhongshan Mall', '112 Katong', 'Bedok Mall', 'Bedok Point', 
    'Century Square', 'Changi Airport', 'Changi City Point', 'City Plaza', 'Djitsun Mall Bedok', 'Downtown East', 
    'East Village', 'Eastpoint Mall', 'Elias Mall', 'Kallang Wave Mall', 'Katong Square', 'Katong V', 
    'Kinex', 'Leisure Park Kallang', 'Loyang Point', 'Our Tampines Hub', 'Parkway Parade', 
    'Paya Lebar Square', 'PLQ Mall', 'Singapore Post Centre', 'Tampines 1', 'Tampines Mall', 'The Flow', 
    'White Sands', '888 Plaza', 'Admiralty Place', 'AMK Hub', 'Beauty World Centre', 'Beauty World Plaza', 
    'Broadway Plaza', 'Buangkok Square', 'Bukit Panjang Plaza', 'Bukit Timah Plaza', 'Causeway Point', 
    'Compass One', 'Djitsun Mall', 'Fajar Shopping Centre', 'Greenridge Shopping Centre', 'Greenwich V', 
    'Heartland Mall', 'Hillion Mall', 'HillV2', 'Hougang 1', 'Hougang Green Shopping Mall', 'Hougang Mall', 
    'Jubilee Square', 'Junction 10', 'Junction 9', 'Keat Hong Shopping Centre', 'KKH The Retail Mall', 
    'Limbang Shopping Centre', 'Lot One', 'Marsiling Mall', 'myVillage @ Serangoon', 'NEX', 'North East', 
    'North West', 'Northpoint City', 'Oasis Terraces', 'Punggol Plaza', 'Rail Mall', 'Rivervale Mall', 
    'Rivervale Plaza', 'Sembawang Shopping Centre', 'Sun Plaza', 'Sunshine Place', 'Teck Whye Shopping Centre', 
    'The Midtown', 'The Seletar Mall', 'Upper Serangoon Shopping Centre', 'Waterway Point', 'West Mall', 
    'Wisteria Mall', 'Woodlands Mart', 'Yew Tee Point', 'Yew Tee Shopping Centre', 'Yew Tee Square', 
    'Alexandra Retail Centre', 'HarbourFront Centre', 'VivoCity', '321 Clementi', 'Alexandra Central', 
    'Anchorpoint', 'Big Box', 'Boon Lay Shopping Centre', 'Fairprice Hub', 'Gek Poh Shopping Centre', 
    'Grantral Mall', 'IMM', 'JCube', 'Jem', 'Jurong Point', 'OD Mall', 'Pioneer Mall', 'Queensway Shopping Centre', 
    'Rochester Mall', 'Taman Jurong Shopping Centre', 'The Clementi Mall', 'The Star Vista', 'Tiong Bahru Plaza', 
    'West Coast Plaza', 'Westgate Mall',
]

len(list_of_shopping_mall)

171

In [35]:
mall_name = []
mall_roadname = []
mall_lat = []
mall_long = []

for i in range(0, len(list_of_shopping_mall)):
    query_address = list_of_shopping_mall[i]
    query_string = 'https://developers.onemap.sg/commonapi/search?searchVal='+str(query_address)+'&returnGeom=Y&getAddrDetails=Y'
    resp = requests.get(query_string)
    try:
        data_mall = json.loads(resp.content)
    except json.decoder.JSONDecodeError:
            print('Could not decode a row')
            continue
    
    if data_mall['found'] != 0:
        mall_name.append(query_address)
        mall_roadname.append(data_mall["results"][0]["ROAD_NAME"])
        mall_lat.append(data_mall["results"][0]["LATITUDE"])
        mall_long.append(data_mall["results"][0]["LONGITUDE"])

        print (str(query_address)+" ,Lat: "+data_mall['results'][0]['LATITUDE'] +" Long: "+data_mall['results'][0]['LONGITUDE'])

    else:
        print ("No Results")

# Store this information in a dataframe
Mall_coords = pd.DataFrame({
    'Mall': mall_name,
    'RoadName': mall_roadname,
    'Latitude': mall_lat,
    'Longitude': mall_long
})

Mall_coords.to_csv('clean_Mall.csv')

Mall_coords

100 AM ,Lat: 1.2745882179999999 Long: 103.84347070000001
313@Somerset ,Lat: 1.3010065690000001 Long: 103.83824659999999
Aperia ,Lat: 1.30974242 Long: 103.8641016
Balestier Hill Shopping Centre ,Lat: 1.326124169 Long: 103.8437095
Bugis Cube ,Lat: 1.298195005 Long: 103.85565550000001
Bugis Junction ,Lat: 1.300117893 Long: 103.8561916
Bugis+ ,Lat: 1.300007152 Long: 103.8556805
Capitol Piazza ,Lat: 1.293063359 Long: 103.85129350000001
Cathay Cineleisure Orchard ,Lat: 1.301497434 Long: 103.8364448
City Gate ,Lat: 1.302347543 Long: 103.86225999999999
City Square Mall ,Lat: 1.31147745 Long: 103.8567808
CityLink Mall ,Lat: 1.292378607 Long: 103.854663
No Results
Duo ,Lat: 1.299216621 Long: 103.8579968
Far East Plaza ,Lat: 1.3073111259999999 Long: 103.83394
Funan ,Lat: 1.2912440059999999 Long: 103.8499848
Great World City ,Lat: 1.293154929 Long: 103.831928
HDB Hub ,Lat: 1.33218812 Long: 103.8470778
No Results
ION Orchard ,Lat: 1.3040425340000001 Long: 103.83188829999999
Junction 8 ,Lat: 1.3501724330000002 Long: 103.8484301
No Results
Liang Court ,Lat: 1.290658604 Long: 103.84454720000001
Liat Towers ,Lat: 1.30510759 Long: 103.83072790000001
Lucky Plaza ,Lat: 1.30446379 Long: 103.83400520000001
Marina Bay Financial Centre Tower 3 ,Lat: 1.279124938 Long: 103.85445759999999
Marina Bay Link Mall ,Lat: 1.2804679429999999 Long: 103.85347009999998
Marina Bay Sands ,Lat: 1.283994101 Long: 103.85945059999999
Marina One ,Lat: 1.27704169 Long: 103.85340190000001
Marina Square ,Lat: 1.291117292 Long: 103.8577583
Midpoint Orchard ,Lat: 1.301783782 Long: 103.8386606
Millenia Walk ,Lat: 1.292046053 Long: 103.8599002
No Results
Ngee Ann City ,Lat: 1.302424172 Long: 103.8346761
Orchard Central ,Lat: 1.300723504 Long: 103.83969240000002
Orchard Gateway ,Lat: 1.300443253 Long: 103.8394428
Orchard Plaza ,Lat: 1.30126533 Long: 103.84115179999999
Orchard Shopping Centre ,Lat: 1.301484998 Long: 103.83788829999999
Palais Renaissance ,Lat: 1.306654845 Long: 103.829588
Peoples Park Centre ,Lat: 1.284869802 Long: 103.8425077
No Results
Plaza Singapura ,Lat: 1.300820718 Long: 103.8450673
No Results
Raffles City ,Lat: 1.294076445 Long: 103.85333179999999
Scotts Square ,Lat: 1.3057629240000002 Long: 103.8330834
Serangoon Plaza ,Lat: 1.310780752 Long: 103.8551468
No Results
Sim Lim Square ,Lat: 1.303022985 Long: 103.85287559999999
Singapore Shopping Centre ,Lat: 1.2981321479999999 Long: 103.8441384
Square 2 ,Lat: 1.320612586 Long: 103.8443315
Suntec City ,Lat: 1.295466756 Long: 103.85858499999999
Tanglin Mall ,Lat: 1.304853421 Long: 103.8238835
Tangs ,Lat: 1.304950056 Long: 103.8329711
Tanjong Pagar Centre ,Lat: 1.276609528 Long: 103.8461808
Tekka Centre ,Lat: 1.30617773 Long: 103.85061
The Centrepoint ,Lat: 1.301978369 Long: 103.839759
The Paragon ,Lat: 1.3039493640000002 Long: 103.8358442
No Results
The Shoppes at Marina Bay Sands ,Lat: 1.284234913 Long: 103.8589822
The South Beach ,Lat: 1.2949880440000001 Long: 103.8562762
Thomson Plaza ,Lat: 1.3543252419999998 Long: 103.8303281
No Results
Velocity ,Lat: 1.319789492 Long: 103.84403359999999
Wheelock Place ,Lat: 1.30453636 Long: 103.8307142
Wisma Atria ,Lat: 1.303698907 Long: 103.8331896
Zhongshan Mall ,Lat: 1.326945045 Long: 103.84655440000002
112 Katong ,Lat: 1.305086818 Long: 103.90509890000001
Bedok Mall ,Lat: 1.3246689740000002 Long: 103.9294055
Bedok Point ,Lat: 1.324801026 Long: 103.932384
Century Square ,Lat: 1.3523611309999999 Long: 103.9437848
Changi Airport ,Lat: 1.357220256 Long: 103.9873046
Changi City Point ,Lat: 1.334036379 Long: 103.9629176
City Plaza ,Lat: 1.314805223 Long: 103.8934183
Djitsun Mall Bedok ,Lat: 1.326053199 Long: 103.92960459999999
Downtown East ,Lat: 1.377775842 Long: 103.9547736
East Village ,Lat: 1.331778949 Long: 103.94623670000001
Eastpoint Mall ,Lat: 1.342586441 Long: 103.9530723
Elias Mall ,Lat: 1.378570261 Long: 103.9419891
Kallang Wave Mall ,Lat: 1.303843272 Long: 103.8727507
Katong Square ,Lat: 1.3048533709999999 Long: 103.90457420000001
Katong V ,Lat: 1.303850304 Long: 103.9028504
Kinex ,Lat: 1.314692135 Long: 103.8944805
Leisure Park Kallang ,Lat: 1.302337453 Long: 103.87644920000001
Loyang Point ,Lat: 1.36645364 Long: 103.9645985
Our Tampines Hub ,Lat: 1.353101202 Long: 103.9408486
Parkway Parade ,Lat: 1.301080033 Long: 103.9052818
Paya Lebar Square ,Lat: 1.318675756 Long: 103.89255059999999
PLQ Mall ,Lat: 1.317482311 Long: 103.8928322
Singapore Post Centre ,Lat: 1.318871844 Long: 103.8947671
Tampines 1 ,Lat: 1.354315565 Long: 103.9450195
Tampines Mall ,Lat: 1.3525802519999999 Long: 103.94469620000001
The Flow ,Lat: 1.30455858 Long: 103.9042117
White Sands ,Lat: 1.372398981 Long: 103.94974920000001
888 Plaza ,Lat: 1.437130524 Long: 103.79528990000001
Admiralty Place ,Lat: 1.439880955 Long: 103.80179100000001
AMK Hub ,Lat: 1.3693892269999999 Long: 103.848478
Beauty World Centre ,Lat: 1.342412642 Long: 103.7765394
Beauty World Plaza ,Lat: 1.341787998 Long: 103.77630409999999
Broadway Plaza ,Lat: 1.371936464 Long: 103.8459738
Buangkok Square ,Lat: 1.384334266 Long: 103.88162309999998
Bukit Panjang Plaza ,Lat: 1.379916507 Long: 103.7643171
Bukit Timah Plaza ,Lat: 1.338631653 Long: 103.77858540000001
Causeway Point ,Lat: 1.4360886769999999 Long: 103.78601
Compass One ,Lat: 1.392094156 Long: 103.89498
Djitsun Mall ,Lat: 1.326053199 Long: 103.92960459999999
Fajar Shopping Centre ,Lat: 1.384005825 Long: 103.77102959999999
Greenridge Shopping Centre ,Lat: 1.385417687 Long: 103.7662355
Greenwich V ,Lat: 1.3876033019999998 Long: 103.86942359999999
Heartland Mall ,Lat: 1.359544509 Long: 103.8851691
Hillion Mall ,Lat: 1.378498681 Long: 103.76302290000001
HillV2 ,Lat: 1.363550958 Long: 103.76423609999999
Hougang 1 ,Lat: 1.375667283 Long: 103.8794503
Hougang Green Shopping Mall ,Lat: 1.379317835 Long: 103.88784709999999
Hougang Mall ,Lat: 1.3724367830000002 Long: 103.89372390000001
No Results
Junction 10 ,Lat: 1.380605125 Long: 103.7600416
Junction 9 ,Lat: 1.433031982 Long: 103.8416008
Keat Hong Shopping Centre ,Lat: 1.377439635 Long: 103.7443832
No Results
Limbang Shopping Centre ,Lat: 1.392242406 Long: 103.74319100000001
Lot One ,Lat: 1.385069923 Long: 103.7452389
Marsiling Mall ,Lat: 1.433512535 Long: 103.7797469
No Results
NEX ,Lat: 1.3506755209999999 Long: 103.87186159999999
North East ,Lat: 1.352915886 Long: 103.9401979
North West ,Lat: 1.435044948 Long: 103.7868262
Northpoint City ,Lat: 1.428113577 Long: 103.83606309999999
Oasis Terraces ,Lat: 1.402634601 Long: 103.91327059999999
Punggol Plaza ,Lat: 1.394184094 Long: 103.9129764
Rail Mall ,Lat: 1.35773806 Long: 103.76814209999999
Rivervale Mall ,Lat: 1.3922173269999998 Long: 103.90447309999999
Rivervale Plaza ,Lat: 1.385371516 Long: 103.90184959999999
Sembawang Shopping Centre ,Lat: 1.4418532530000001 Long: 103.8248324
Sun Plaza ,Lat: 1.4482265380000001 Long: 103.8194621
Sunshine Place ,Lat: 1.377897277 Long: 103.73901550000001
Teck Whye Shopping Centre ,Lat: 1.380047726 Long: 103.7524646
The Midtown ,Lat: 1.37047941 Long: 103.8951285
The Seletar Mall ,Lat: 1.391393061 Long: 103.87606770000001
Upper Serangoon Shopping Centre ,Lat: 1.353480883 Long: 103.8788284
Waterway Point ,Lat: 1.4064261630000001 Long: 103.90223809999999
West Mall ,Lat: 1.3501891659999998 Long: 103.749022
Wisteria Mall ,Lat: 1.417999263 Long: 103.8412365
Woodlands Mart ,Lat: 1.44564787 Long: 103.7981623
Yew Tee Point ,Lat: 1.397057415 Long: 103.7466621
No Results
Yew Tee Square ,Lat: 1.3980473619999998 Long: 103.7470848
Alexandra Retail Centre ,Lat: 1.274148936 Long: 103.80139940000001
HarbourFront Centre ,Lat: 1.2637968290000001 Long: 103.820219
VivoCity ,Lat: 1.264394681 Long: 103.82180859999998
321 Clementi ,Lat: 1.3120249179999999 Long: 103.7649605
Alexandra Central ,Lat: 1.287456124 Long: 103.8054147
Anchorpoint ,Lat: 1.28893478 Long: 103.8056078
Big Box ,Lat: 1.331832698 Long: 103.7448792
Boon Lay Shopping Centre ,Lat: 1.346373764 Long: 103.7124728
Fairprice Hub ,Lat: 1.325617678 Long: 103.6784097
Gek Poh Shopping Centre ,Lat: 1.3487440030000002 Long: 103.6982988
Grantral Mall ,Lat: 1.333722109 Long: 103.8875308
IMM ,Lat: 1.334917588 Long: 103.74687709999999
JCube ,Lat: 1.333237851 Long: 103.74019129999999
Jem ,Lat: 1.333054519 Long: 103.74343370000001
Jurong Point ,Lat: 1.339452004 Long: 103.706685
No Results
Pioneer Mall ,Lat: 1.341591087 Long: 103.69702009999999

Queensway Shopping Centre ,Lat: 1.287617926 Long: 103.8033911
Rochester Mall ,Lat: 1.3054076559999999 Long: 103.78844670000001
Taman Jurong Shopping Centre ,Lat: 1.334844875 Long: 103.720462
The Clementi Mall ,Lat: 1.315496754 Long: 103.76457020000001
The Star Vista ,Lat: 1.30697044 Long: 103.7884203
Tiong Bahru Plaza ,Lat: 1.2864712 Long: 103.8271583
West Coast Plaza ,Lat: 1.303742583 Long: 103.7660929
No Results

,Mall,RoadName,Latitude,Longitude
0,100 AM,TRAS STREET,1.2745882179999999,103.84347070000001
1,313@Somerset,ORCHARD ROAD,1.3010065690000001,103.83824659999999
2,Aperia,KALLANG AVENUE,1.30974242,103.8641016
3,Balestier Hill Shopping Centre,BALESTIER ROAD,1.326124169,103.8437095
4,Bugis Cube,NORTH BRIDGE ROAD,1.298195005,103.85565550000001
...,...,...,...,...
151,Taman Jurong Shopping Centre,YUNG SHENG ROAD,1.334844875,103.720462
152,The Clementi Mall,COMMONWEALTH AVENUE WEST,1.315496754,103.76457020000001
153,The Star Vista,VISTA EXCHANGE GREEN,1.30697044,103.7884203
154,Tiong Bahru Plaza,TIONG BAHRU ROAD,1.2864712,103.8271583
155,West Coast Plaza,WEST COAST ROAD,1.303742583,103.7660929

### BusStop Coordinates<a id="subsection2.4"></a>

In [36]:
Bus_coords = pd.read_csv("clean_bus.csv")

Bus_coords

      Busstop_no.  Latitude   Longitude
0           10009  1.282102  103.817225
1           10011  1.277738  103.837497
2           10017  1.278320  103.837626
3           10018  1.279008  103.838604
4           10021  1.277448  103.838389
...           ...       ...         ...
4988         3419  1.271277  103.862977
4989         3421  1.266941  103.859648
4990         3411  1.271593  103.863009
4991         3339  1.274985  103.859500
4992         5009  1.285926  103.849236

[4993 rows x 3 columns]

### Import All Other Relevant Datasets<a id="subsection2.5"></a>

## General Functions<a id="section3"></a>

In [ ]:
#calculate distance between two pairs of lat and long
def distance(x1,y1,x2,y2):
    R = 6373.0
    lat1 = radians(x1)
    lon1 = radians(y1)
    lat2 = radians(x2)
    lon2 = radians(y2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = (sin(dlat/2))**2 + cos(lat1)*cos(lat2)*(sin(dlon/2))**2
    c = 2* atan2(sqrt(a), sqrt(1-a))
    dist = R * c
    return dist